# Generated by Django 4.2.11 on 2025-01-15 18:32

import auditoria.models.auditoria
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_audit_cuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identificador de Auditoría')),
                ('tabla_auditoria', auditoria.models.auditoria.OIDField(verbose_name='Tabla en Auditoría')),
                ('tiempo_auditoria', models.DateTimeField(verbose_name='Tiempo de Auditoría')),
                ('viejo_auditoria', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Valores viejos de auditoría')),
                ('nuevo_auditoria', django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Valores nuevos de auditoría')),
            ],
            options={
                'verbose_name': 'Acción en Tabla de Solicitudes',
                'verbose_name_plural': 'Acciones en Tablas de Solicitudes',
            },
        ),
        migrations.AddConstraint(
            model_name='solicitudes',
            constraint=models.CheckConstraint(check=models.Q(('viejo_auditoria__isnull', False), ('nuevo_auditoria__isnull', False), _connector='OR'), name='auditoria_solicitudes_no_nula'),
        ),
    ]
