from django.urls import URLPattern, path

from . import views

app_name: str = 'cuentas'
urlpatterns: list[URLPattern] = [
    path(
        'crear_cuenta/',
        views.VistaCreacionCuenta.as_view(),
        name='crear_cuenta'
    ),
    path(
        'activar_cuenta/<str:uidb64>/<str:token>/',
        views.VistaActivacionCuenta.as_view(),
        name='activar_cuenta',
    ),
    path(
        'iniciar_sesion/',
        views.VistaInicioSesion.as_view(),
        name='iniciar_sesion'
    ),
    path(
        'autenticar_usuario/<str:uidb64>/<str:token>/',
        views.VistaAutenticacionUsuario.as_view(),
        name='autenticar_usuario',
    ),
    path(
        'cerrar_sesion/',
        views.VistaCierreSesion.as_view(),
        name='cerrar_sesion'
    ),
    path(
        'recuperar_cuenta/',
        views.VistaRecuperacionCuenta.as_view(),
        name='recuperar_cuenta'
    ),
    path(
        'recuperar_cuenta/hecho/',
        views.VistaRecuperacionHecha.as_view(),
        name='recuperar_hecho',
    ),
    path(
        'recuperar_contrasenia/<str:uidb64>/<str:token>/',
        views.VistaRecuperacionContrasenia.as_view(),
        name='recuperar_contrasenia',
    ),
    path(
        'recuperar_contrasenia/completo/',
        views.VistaRecuperacionCompleta.as_view(),
        name='recuperar_completo',
    ),
    path(
        'cambiar_contrasenia/',
        views.VistaCambioContrasenia.as_view(),
        name='cambiar_contrasenia'
    ),
    path(
        'cambiar_contrasenia/hecho/',
        views.VistaCambioHecho.as_view(),
        name='cambiar_hecho',
    ),
    path(
        'perfiles/',
        views.VistaPerfil.as_view(),
        name='perfil'
    ),
    path(
        'notificaciones/',
        views.VistaNotificaciones.as_view(),
        name='notificaciones'
    ),
    path(
        'comitente/',
        views.VistaComitente.as_view(),
        name='comitente'
    ),
    path(
        'responsable/',
        views.VistaResponsableTecnico.as_view(),
        name='responsable_tecnico'
    ),
    path(
        'secretario/',
        views.VistaSecretario.as_view(),
        name='secretario'
    ),
    path(
        'ayudante/',
        views.VistaAyudante.as_view(),
        name='ayudante'
    ),
    path(
        'registrar_responsable/',
        views.VistaRegistroResponsable.as_view(),
        name='registrar_responsable'
    ),
    path(
        'registrar_comitente/',
        views.VistaRegistroComitente.as_view(),
        name='registrar_comitente'
    ),
]
