# Generated by Django 4.2.11 on 2025-02-18 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('solicitud_servicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='solicitudes.solicitudservicio', verbose_name='Solicitud para Convenio')),
                ('tiempo_creacion_convenio', models.DateTimeField(auto_now_add=True, verbose_name='Tiempo de Creación de Convenio')),
                ('archivo_convenio', models.FileField(null=True, upload_to='convenios/', verbose_name='Archivo de Convenio')),
                ('tiempo_subida_convenio', models.DateTimeField(null=True, verbose_name='Tiempo de Subida de Convenio')),
                ('cancelacion_convenio', models.DateTimeField(default=None, null=True, verbose_name='Tiempo de Cancelación de Convenio')),
                ('causa_cancelacion_convenio', models.TextField(default=None, null=True, verbose_name='Causa de Cancelación de Convenio')),
                ('convenio_suspendido', models.BooleanField(verbose_name='Si Convenio está Suspendido')),
            ],
            options={
                'verbose_name_plural': 'convenios',
                'db_table': 'convenios',
            },
        ),
        migrations.CreateModel(
            name='FirmaOrden',
            fields=[
                ('id_firma_orden', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de Firma en Orden')),
                ('pagina_firma', models.PositiveSmallIntegerField(verbose_name='Página de Firma')),
                ('coord_x_firma', models.FloatField(verbose_name='Coordenada X de Firma')),
                ('coord_y_firma', models.FloatField(verbose_name='Coordenada Y de Firma')),
                ('tiempo_firma', models.DateTimeField(null=True, verbose_name='Tiempo de Firma')),
                ('documento_firmado', models.FileField(null=True, upload_to='ordenes_parciales/', verbose_name='Documento firmado')),
            ],
            options={
                'verbose_name': 'firma en orden',
                'verbose_name_plural': 'firmas de órdenes',
                'db_table': 'firmas_ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('solicitud_servicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='solicitudes.solicitudservicio', verbose_name='Solicitud para Orden de Servicio')),
                ('numero_orden_servicio', models.PositiveIntegerField(unique=True, verbose_name='Número de Orden de Servicio')),
                ('tiempo_creacion_orden', models.DateTimeField(auto_now_add=True, verbose_name='Tiempo de Creación de Orden de Servicio')),
                ('firma_digital', models.BooleanField(verbose_name='Si la Firma de Orden de Servicio es digital')),
                ('archivo_orden_original', models.FileField(null=True, upload_to='ordenes_originales/', verbose_name='Archivo Original de Orden de Servicio')),
                ('archivo_orden_firmada', models.FileField(null=True, upload_to='ordenes_firmadas/', verbose_name='Archivo de Orden de Servicio Firmada')),
                ('ultima_accion_orden', models.DateTimeField(auto_now=True, verbose_name='Tiempo de Última Acción en Orden de Servicio')),
                ('cancelacion_orden', models.DateTimeField(default=None, null=True, verbose_name='Tiempo de Cancelación de Orden de Servicio')),
                ('causa_cancelacion_orden', models.TextField(default=None, null=True, verbose_name='Causa de Cancelación de Orden de Servicio')),
                ('orden_suspendida', models.BooleanField(verbose_name='Si Orden de Servicio está Suspendida')),
            ],
            options={
                'verbose_name': 'orden de servicio',
                'verbose_name_plural': 'órdenes de servicio',
                'db_table': 'ordenes_servicio',
            },
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.CheckConstraint(check=models.Q(('archivo_orden_firmada__isnull', True), ('archivo_orden_original__isnull', False), _connector='OR'), name='primero_orden_original_despues_firmada'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cancelacion_orden__isnull', True), ('causa_cancelacion_orden__isnull', True)), models.Q(('cancelacion_orden__isnull', False), ('causa_cancelacion_orden__isnull', False)), _connector='OR'), name='orden_cancelada_con_causa_o_no'),
        ),
        migrations.AddField(
            model_name='firmaorden',
            name='orden_firmada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firmas.ordenservicio', verbose_name='Orden Firmada'),
        ),
        migrations.AddField(
            model_name='firmaorden',
            name='usuario_firmante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Firmante'),
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cancelacion_convenio__isnull', True), ('causa_cancelacion_convenio__isnull', True)), models.Q(('cancelacion_convenio__isnull', True), ('causa_cancelacion_convenio__isnull', False), ('archivo_convenio__isnull', True)), _connector='OR'), name='convenio_cancelado_con_causa_y_sin_archivo_o_no'),
        ),
        migrations.AddConstraint(
            model_name='firmaorden',
            constraint=models.UniqueConstraint(fields=('orden_firmada', 'usuario_firmante'), name='usuario_unico_por_orden'),
        ),
        migrations.AddConstraint(
            model_name='firmaorden',
            constraint=models.UniqueConstraint(fields=('orden_firmada', 'pagina_firma', 'coord_x_firma', 'coord_y_firma'), name='lugar_firma_unico_por_orden'),
        ),
    ]
