from django.urls import URLPattern, path

from . import views

app_name: str = "solicitudes"
urlpatterns: list[URLPattern] = [
    path(
        "comitente/solicitudes/",
        views.VistaListaSolicitudesComitente.as_view(),
        name="lista_solicitudes_comitente"
    ),
    path(
        "comitente/solicitudes/csv/",
        views.VistaCsvSolicitudesComitente.as_view(),
        name="csv_solicitudes_comitente"
    ),
    path(
        "responsable/solicitudes/csv/",
        views.VistaCsvSolicitudesResponsable.as_view(),
        name="csv_solicitudes_responsable"
    ),
    path(
        "comitente/solicitudes/reporte/",
        views.VistaReporteSolicitudesComitente.as_view(),
        name="reporte_solicitudes_comitente"
    ),
    path(
        "responsable/solicitudes/reporte/",
        views.VistaReporteSolicitudesResponsable.as_view(),
        name="reporte_solicitudes_responsable"
    ),
    path(
        "comitente/solicitudes/informe/",
        views.VistaInformeSolicitudesComitente.as_view(),
        name="informe_solicitudes_comitente"
    ),
    path(
        "responsable/solicitudes/informe/",
        views.VistaInformeSolicitudesResponsable.as_view(),
        name="informe_solicitudes_responsable"
    ),
    path(
        "comitente/solicitudes/informe/reporte/",
        views.VistaReporteInformeSolicitudesComitente.as_view(),
        name="reporte_informe_solicitudes_comitente"
    ),
    path(
        "responsable/solicitudes/informe/reporte/",
        views.VistaReporteInformeSolicitudesResponsable.as_view(),
        name="reporte_informe_solicitudes_responsable"
    ),
    path(
        "comitente/solicitudes/nuevo/",
        views.VistaNuevaSolicitud.as_view(),
        name="agregar_solicitud"
    ),
    path(
        "comitente/solicitudes/<int:solicitud>/recuperar/",
        views.VistaRecuperarSolicitudComitente.as_view(),
        name="recuperar_solicitud_comitente"
    ),
    path(
        "comitente/solicitudes/<int:solicitud>/reporte/",
        views.VistaReporteSolicitudComitente.as_view(),
        name="reporte_solicitud_comitente"
    ),
    path(
        "responsable/solicitudes/<int:solicitud>/reporte/",
        views.VistaReporteSolicitudResponsable.as_view(),
        name="reporte_solicitud_responsable"
    ),
    path(
        "comitente/solicitudes/<int:solicitud>/aceptar/",
        views.VistaAceptarSolicitudComitente.as_view(),
        name="aceptar_solicitud_comitente"
    ),
    path(
        "comitente/solicitudes/<int:solicitud>/rechazar/",
        views.VistaRechazarSolicitudComitente.as_view(),
        name="rechazar_solicitud_comitente"
    ),
    path(
        "comitente/solicitudes/<int:solicitud>/decidir/",
        views.VistaDecisionResponsables.as_view(),
        name="decidir_responsables"
    ),
    path(
        "responsable/solicitudes/",
        views.VistaListaSolicitudesResponsable.as_view(),
        name="lista_solicitudes_responsable"
    ),
    path(
        "responsable/solicitudes/<int:solicitud>/apuntarse/",
        views.VistaAutoadjudicarResponsable.as_view(),
        name="autoadjudicar_responsable"
    ),
    path(
        "responsable/solicitudes/<int:solicitud>/aceptar/",
        views.VistaAceptarSolicitudResponsable.as_view(),
        name="aceptar_solicitud_responsable"
    ),
    path(
        "responsable/solicitudes/<int:solicitud>/rechazar/",
        views.VistaRechazarSolicitudResponsable.as_view(),
        name="rechazar_solicitud_responsable"
    ),
    path(
        "responsable/solicitudes/<int:solicitud>/proponer/",
        views.VistaNuevaPropuesta.as_view(),
        name="nueva_propuesta"
    ),
    path(
        "comitente/solicitudes/<int:solicitud>/propuesta/",
        views.VistaRevisarPropuestaComitente.as_view(),
        name="revisar_propuesta_comitente"
    ),
    path(
        "responsable/solicitudes/<int:solicitud>/propuesta/",
        views.VistaRevisarPropuestaResponsableTecnico.as_view(),
        name="revisar_propuesta_responsable_tecnico"
    ),
]
