from django.urls import URLPattern, path

from . import views

app_name: str = "firmas"
urlpatterns: list[URLPattern] = [
    path(
        "comitente/ordenes/",
        views.VistaListaOrdenesComitente.as_view(),
        name="lista_ordenes_comitente"
    ),
    path(
        "comitente/ordenes/<int:orden>/firmar/",
        views.VistaFirmaOrdenComitente.as_view(),
        name="firma_orden_comitente"
    ),
    path(
        "comitente/ordenes/informe/",
        views.VistaInformeOrdenesComitente.as_view(),
        name="informe_ordenes_comitente"
    ),
    path(
        "responsable/ordenes/",
        views.VistaListaOrdenesResponsable.as_view(),
        name="lista_ordenes_responsable"
    ),
    path(
        "responsable/ordenes/<int:orden>/firmar/",
        views.VistaFirmaOrdenResponsable.as_view(),
        name="firma_orden_responsable"
    ),
    path(
        "responsable/ordenes/informe/",
        views.VistaInformeOrdenesResponsable.as_view(),
        name="informe_ordenes_responsable"
    ),
    path(
        "comitente/convenios/",
        views.VistaListaConveniosComitente.as_view(),
        name="lista_convenios_comitente"
    ),
    path(
        "comitente/convenios/informe/",
        views.VistaInformeConveniosComitente.as_view(),
        name="informe_convenios_comitente"
    ),
    path(
        "responsable/convenios/",
        views.VistaListaConveniosResponsable.as_view(),
        name="lista_convenios_responsable"
    ),
    path(
        "responsable/convenios/informe/",
        views.VistaInformeConveniosResponsable.as_view(),
        name="informe_convenios_responsable"
    ),
    path(
        "secretario/convenios/",
        views.VistaListaConveniosSecretario.as_view(),
        name="lista_convenios_secretario"
    ),
    path(
        "secretario/convenios/<int:convenio>/subir/",
        views.VistaSubidaConvenio.as_view(),
        name="subir_convenio"
    ),
    path(
        "secretario/ordenes/",
        views.VistaListaOrdenesSecretario.as_view(),
        name="lista_ordenes_secretario"
    ),
    path(
        "secretario/ordenes/<int:orden>/firmar/",
        views.VistaFirmaOrdenSecretario.as_view(),
        name="firma_orden_secretario"
    ),
    path(
        "ayudante/ordenes/",
        views.VistaListaOrdenesAyudante.as_view(),
        name="lista_ordenes_ayudante"
    ),
    path(
        "ayudante/ordenes/<int:orden>/",
        views.VistaOrdenServicio.as_view(),
        name="generar_archivo"
    ),
    path(
        "ayudante/ordenes/<int:orden>/subir/",
        views.VistaSubidaOrden.as_view(),
        name="subir_archivo"
    ),
]
