# Generated by Django 4.2.11 on 2025-02-15 20:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de servicio')),
                ('pagado', models.BooleanField(default=False, verbose_name='Si servicio está pagado')),
                ('completado', models.BooleanField(default=False, verbose_name='Si servicio está completo')),
                ('convenio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='firmas.convenio', verbose_name='Convenio anexo')),
                ('orden_servicio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='firmas.ordenservicio', verbose_name='Orden de Servicio anexa')),
                ('cancelacion_servicio', models.DateTimeField(default=None, null=True, verbose_name='Tiempo de Cancelación de Servicio')),
                ('causa_cancelacion_servicio', models.TextField(default=None, null=True, verbose_name='Causa de Cancelación de Servicio')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de Progreso')),
                ('descripcion_progreso', models.TextField(verbose_name='Descripción de Progreso')),
                ('porcentaje_progreso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Progreso')),
                ('servicio_progreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio', verbose_name='Servicio de Progreso')),
            ],
            options={
                'db_table': 'progresos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de Pago')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto de Pago')),
                ('comitente_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas.comitente', verbose_name='Comitente de Pago')),
                ('servicio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio', verbose_name='Servicio de Pago')),
            ],
            options={
                'verbose_name': 'pago de servicio',
                'verbose_name_plural': 'pagos de servicios',
                'db_table': 'pagos',
            },
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('orden_servicio__isnull', True), ('convenio__isnull', False)), models.Q(('orden_servicio__isnull', False), ('convenio__isnull', True)), _connector='OR'), name='u_orden_servicio_o_convenio'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cancelacion_servicio__isnull', True), ('causa_cancelacion_servicio__isnull', True)), models.Q(('cancelacion_servicio__isnull', False), ('causa_cancelacion_servicio__isnull', False)), _connector='OR'), name='servicio_cancelado_con_causa_o_no'),
        ),
        migrations.AddConstraint(
            model_name='progreso',
            constraint=models.CheckConstraint(check=models.Q(('porcentaje_progreso__gte', models.Value(Decimal('0'), models.DecimalField())), ('porcentaje_progreso__lte', models.Value(Decimal('100'), models.DecimalField()))), name='porcentaje_progreso_valido'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('monto_pago__gt', Decimal('0'))), name='monto_pago_valido'),
        ),
    ]
